### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by altro3**
Gradle 7.4.2
Micronaut 3.4.2
Spotless 6.5.0

Removes redundant dependency httpclient

### CODE REVIEW

**Comment by altro3** [comment]
@GoodforGod Hi! Some dependency versions updates and fix with redundant dependency `implementation "org.apache.httpcomponents:httpclient:4.5.13"`

**Comment by GoodforGod** [comment]
Hello @altro3 and thanks for PR!
1. httpclient is actually used by ArangoDB driver (it uses exactly this version) and this import fixes incorrect ArangoDB driver behavior when some versions didn't transiently include http client dependency and you had to manually include it in project, so this Arango bug is fixed by including transitive dependency here in this lib for better devEx
2. Micronaut is already 3.4.2 and this is actually non essential, cause this is library and Micronaut version project uses is essential (project for app that uses this lib)
3. This is actually bad practice to use "latest" tag for docker images, cause this introduces non reproduceable builds, so it is recommended to use fixed tags
4. Others dependencies are like spotless and gradle are common across many other code bases I use, so this change doesn't introduce any improvements or other stuff

But still thank you for interest in project, always open for any improvements or bug reports!

**Comment by GoodforGod** [comment]
This is still the case if you use HTTP_JSON / HTTP_VPACK as a protocol (which can be the case)

For
```
public class Check {

    public static void main(String[] args) {
        final Map<String, Object> properties = new HashMap<>();
        properties.put("arangodb.port", 8529);
        properties.put("arangodb.database", "custom");
        properties.put("arangodb.protocol", "HTTP_VPACK");

        try (final ApplicationContext context = ApplicationContext.run(properties)) {
            final ArangoClient clientAsync = context.getBean(ArangoClient.class);
            final BaseDocument document = new BaseDocument();
            String id = UUID.randomUUID().toString();
            document.setKey(id);
            final DocumentCreateEntity<BaseDocument> created = clientAsync.db().collection("custom").insertDocument(document);
            final BaseDocument found = clientAsync.db().collection("custom").getDocument(id, BaseDocument.class);

            System.out.println(found);
        }
    }
}
```

Results in:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/conn/HttpClientConnectionManager
	at com.arangodb.internal.http.HttpConnection$Builder.build(HttpConnection.java:160)
	at com.arangodb.internal.http.HttpConnectionFactory.create(HttpConnectionFactory.java:53)
	at com.arangodb.internal.net.ConnectionPoolImpl.createConnection(ConnectionPoolImpl.java:58)
	at com.arangodb.internal.net.ConnectionPoolImpl.connection(ConnectionPoolImpl.java:69)
	at com.arangodb.internal.net.HostImpl.connection(HostImpl.java:54)
	at com.arangodb.internal.http.HttpCommunication.execute(HttpCommunication.java:85)
	at com.arangodb.internal.http.HttpCommunication.execute(HttpCommunication.java:76)
	at com.arangodb.internal.http.HttpProtocol.execute(HttpProtocol.java:45)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:71)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:61)
	at com.arangodb.internal.ArangoCollectionImpl.insertDocument(ArangoCollectionImpl.java:56)
	at com.arangodb.internal.ArangoCollectionImpl.insertDocument(ArangoCollectionImpl.java:49)
	at io.goodforgod.Check.main(Check.java:33)
Caused by: java.lang.ClassNotFoundException: org.apache.http.conn.HttpClientConnectionManager
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 13 more
```

So changing this will result in breaking change and major version update, so don't think that this is suitable.

Thanks for your PR anyway, always open for bugs or improvements

**Comment by altro3** [comment]
@GoodforGod Thanks for your comment. Ok, understood. Only one moment about docker image version: in all other tests you use `latest` and only here you use old version. That's why I changed it.

**Comment by GoodforGod** [comment]
Looks like a mistake I used to do, I was also long ago using `latest` as you see and only then come to conclusion based on experience that this is actually not a good move as it can be seen in the first place, we all learn and evolve 🙂 

Thanks for pointing out, will change this in DEV branch for next release!

**Pull request closed without merging**
